spring:
   application:
      name: APIGateway
   cloud:
      gateway:
        discovery:
          locator:
            enabled: true
        routes:
            - id: OrderService
              uri: lb://OrderService
              predicates:
              - Path=/order/**
            - id: ProductService
              uri: lb://ProductService
              predicates:
              - Path=/product/**
            - id: PaymentService
              uri: lb://PaymentService
              predicates:
              - Path=/payment/**
            - id: DiscoveryServer
              uri: http://localhost:8761
              predicates:
              - Path=/eureka/web
              filters:
              - SetPath=/
            - id: DiscoveryServerStatic
              uri: http://localhost:8761
              predicates:
              - Path=/eureka/**
   security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/spring-boot-microservices-realm
              
server:
   port: 8989


   
eureka:
   client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
         defaultZone: http://localhost:8761/eureka
   instance:
      hostname: localhost
      prefer-ip-address: true
